# Generated by Django 2.2 on 2020-08-31 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='category name')),
                ('description', models.TextField(blank=True, verbose_name='category description')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='clothing name')),
                ('image', models.ImageField(blank=True, upload_to='clothings_images')),
                ('short_descript', models.CharField(blank=True, max_length=64, verbose_name='clothing short description')),
                ('description', models.TextField(blank=True, verbose_name='clothing description')),
                ('designer_info', models.TextField(blank=True, verbose_name='about designer')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='clothing price')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantity at warehouse')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ClothingCategory', verbose_name='clothing category')),
            ],
            options={
                'verbose_name': 'clothing',
                'verbose_name_plural': 'clothings',
            },
        ),
    ]
