# Generated by Django 2.2 on 2020-09-15 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clothingcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
