# Generated by Django 2.2 on 2020-09-15 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopcartapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_bag', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
